### ISSUE TITLE
blocco su RPI B+

### ISSUE THREAD

**Issue by nixiam** [Zanzibar82/plugin.video.streamondemand#17]
Ciao a tutti,
innanzitutto grazie per il plugin sviluppato! 
Ho un problema: provando il plugin su kodi 15 installato su PC tutto ok, ma quando tento di far partire una riproduzione sul plugin installato sul raspberry (sempre con kodi 15 tramite OSMC), appena seleziono "Guarda il video" Kodi si blocca e devo riavviare il raspberry via SSH con "sudo reboot".

Sapere a cosa può essere dovuto? Se può essere utile posto i log.

Ciao e Grazie

**Comment by dentaku65** [comment]
per OSMC guarda questo post
https://discourse.osmc.tv/t/opendemuxstream-error-creating-demuxer/7048/15
Ricordati di avere l'ultima versione di SOD installata

**Comment by hexpl0it** [comment]
Nixiam se hai risolto possiamo chiudere la issue, in caso contrario potresti postare i log?

**Comment by talksina** [comment]
adesso su windows sembra funzionare: clicco sul titolo, mi dice fastvideo, clicco, mi compare "guarda video" o "scarica", ma poi non parte - credo però che non parta perché 'sta macchina è sotto proxy. Stasera provo sulla macchina di casa e vi faccio sapere, a meno che non vogliate il log pure di questa prova qui; anche se, se l'errore è su fastvideo, SoD credo non c'entri più...

**Comment by nixiam** [comment]
Diciamo che si è risolto da solo. Al riavvio del raspberry è andato tutto ok, solamente che su windows al click del video parte subito la connessione al sito, mentre sul raspberry bisogna attendere circa 10 secondi.

**Comment by hexpl0it** [comment]
Il raspberry ha caratteristiche molto inferiori rispetto a una macchina "normale" passami il termine :'D processore e RAM sono più piccoli è normale ci metta un po di più ad elaborare il codice

**Comment by dentaku65** [comment]
anche perche è il raspberry rpi e non rpi2 che invece è molto performante; al posto di osmc prova ad installarci xbian o openelec per vedere se con il vecchio rasp è un po' più reattivo; osmc gira molto bene sul rpi2 ma sull'rpi ho qualche dubbio.

**Comment by acca** [comment]
Ho lo stesso problema. Utilizzo osmc v15.2 e SOD v5.1.8 su RPI e quando provo ad avviare uno stream osmc si blocca. Unico modo per risolvere è riavviare tramite `sudo reboot`.
Ho provato ad installare mplayer, ffmpeg ecc come segnalato qui: https://github.com/Zanzibar82/plugin.video.streamondemand/issues/17#issuecomment-164710659 da dentaku65 ma senza nessun risultato positivo.
Allego kodi.log
Avete qualche idea per risolvere ?
[kodi.log.zip](https://github.com/Zanzibar82/plugin.video.streamondemand/files/76394/kodi.log.zip)

**Comment by acca** [comment]
Come non detto, ho re-installato osmc ed ora il mio problema è scomparso. L'errore era sicuramente legato a qualche setting errato nell' installazione precedente.
