### ISSUE TITLE
Errore su guardaserie.net - fastvideo

### ISSUE THREAD

**Issue by talksina** [Zanzibar82/plugin.video.streamondemand#18]
Salve,
installando l'ultima release su due macchine con Kodi, ho notato degli errori sulle serie tv di guardaserie.
1. entro su "serie tv", da "scegli categoria"
2. entro su guardaserie
3. seleziono la serie
4. do invio sull'episodio.
Anziché comparire il titolo della fonte, che per guardaserie era "fast video", Kodi emette un segnale acustico e rimane nella finestra con la lista episodi.
allego il log - se serve, poi, stasera vi passo anche il log di Kodi per mac.
Log qui:
https://www.dropbox.com/s/cpd39bhnok9pbwr/log%20kodi.zip?dl=0

**Comment by dentaku65** [comment]
guardaserie ha dei problemi lo script in toto... per i log usa pastebin per piacere

**Comment by talksina** [comment]
OK per guardaserie - appena è fixato me ne accorgerò da sola penso :)
Per i log - http://pastebin.com/njU1rdk7
E' la prima volta che uso pastebin per cui sicuramente ho sbagliato
qualcosa, non ho specificato syntax highlighting

**Comment by Zanzibar82** [comment]
Il problema nel canale è la stringa:

url = scrapertools.get_match( data.lower(), 'src="([^"]+)"' )

**Comment by talksina** [comment]
e quindi - dovrei cambiare qualche cosa io, o aspetto semplicemente
che esca la versione nuova dell'add-on?
Rinnovo i complimenti per l'add-on, già espressi su fb nel post
riguardo a quelli che domandano tv a pagamento et similia
elena brescacin

**Comment by hexpl0it** [comment]
No devi aspettare che sistemino il canale.. Se riesco dopo lo sistemo io e faccio il pull così evitiamo un po di lavoro ai capi ;D

**Comment by dentaku65** [comment]
grande hexpl0it

**Comment by talksina** [comment]
provata disinstallazione e reinstallazione pulita anche da mac.
Lista canali aggiornata.
Ma niente - GuardaSerie continua a non andare.
Invece altri servizi di streaming vanno.
Come promesso per completezza vi giro anche il log del mac, probabilmente questo ha più roba dato che è la mia macchina principale e ho molti più componenti su.
http://pastebin.com/CtkNnnKf <http://pastebin.com/CtkNnnKf>

**Comment by dentaku65** [comment]
talksina, guardaserie ha un problema nel nostro script, quando il canale verrà sistemato viene aggiornato automaticamente...

**Comment by Zanzibar82** [comment]
L'errore purtroppo non è solo dove pensavo, a quanto pare c'è un problema di connection/closed a causa degli headers che non riesco a sistemare. Se ci sono idee sono benvenute.

**Comment by Zanzibar82** [comment]
Quasi ci sarebbe da vergognarsi per quanto era semplice la soluzione al problema.
Se non ci sono più problemi chiudete la issue :+1:

**Comment by talksina** [comment]
> purtroppo fino a stasera non posso fare test...
Ora vado in ufficio sotto proxy aziendale quindi potrebbe non funzionare x forza, stasera rientro e provo, dopo di che se non ci son più guai vi dico di chiuderla :)
buon lavoro

**Comment by hexpl0it** [comment]
Hahahah :D grande Zanzibar :) confermo anche io ora funziona

**Comment by dentaku65** [comment]
solved
