### ISSUE TITLE
Bad code attribution.

### ISSUE THREAD

**Issue by Thynisen** [Zanzibar82/plugin.video.streamondemand#19]
Just for information in your code take care at first creator, eg for your source openload.py

DrZ3r0 have posted his code the october 4th >> https://github.com/Zanzibar82/plugin.video.streamondemand/commits/master/servers/openload.py
And we can see his name in credit.

But you can see the same code sptember 19th from Djeman and not DrZ3r0 
https://github.com/LordVenom/venom-xbmc-addons-beta/commits/master/plugin.video.vstream/resources/lib/aadecode.py

And for this one, he have make a mix with this other script
https://github.com/crackinglandia/python-jjdecoder/blob/master/jjdecode.py
with removing previous credits.

IDK, if it's the same person but not good for repution.

Thx to correct that, and take a look for other code proposed by this user.

**Comment by Zanzibar82** [comment]
@Thynisen Sorry, just added credits to the head of the file, we'll pay more attention from now on.
I'm sure it's about distraction and it's not intended to damage anyone.
@Dr-Zer0 is a proven skilled developer, but of course nobody has the reply to any issue,
so as anybody else in the open-source ambient he went looking for other people's solution to the matter. He just forgot to mention the source; so let's pay more attention from now on.
Thanks for opening the issue in merit.

**Comment by Dr-Zer0** [comment]
I apologize, I forgot to mention the author of the source code.
This link: https://github.com/LordVenom/venom-xbmc-addons-beta/commits/master/plugin.video.vstream/resources/lib/aadecode.py was reported by a member of our forum.
