### ISSUE TITLE
Not working on Kodi 17

### ISSUE THREAD

**Issue by simonepsp** [Zanzibar82/plugin.video.streamondemand#29]
Hi,
I'm having some issues running your plugin on Kodi 17 (on Apple tv 4).
When I click on any streaming website I get this error:
![421207067_17923894137089682339](https://cloud.githubusercontent.com/assets/11884948/13842389/309e8932-ec2e-11e5-9053-654741dd3fef.jpg)

I know Kodi 17 is still in alpha stage and this could be the reason...
Thanks for your time and your work on this addon. If possibile, please point me out what's the solution.

Bye

**Comment by dentaku65** [comment]
Hello,
ATV4 is not fully supported by Kodi; choose a different device/system, personally I strongly suggest to use RPI2 or RPI3
