### ISSUE TITLE
Errore streamingondemeand su Openelec

### ISSUE THREAD

**Issue by ginobyte** [Zanzibar82/plugin.video.streamondemand#32]
Salve a tutti, ho comprato qualche settimana fa un bellissimo rapberryPI3, fantastico e potente...con l'idea di costruirmi il mio mediacenter. Ho installato Openelec (l'ultima versione stabile) e poi dopo averlo scaricato dal vs. repository la versione 5.2.4 di Streamindondemand, alla selezione di qualsiasi elemento dell'add-on mi appare un messaggio di errore, e controllando sul log di kodi sembra che vada in errore la funzione get directory....se serve posso recuperare e postare il log, stessa cosa fatta su kodi su pc con windows10 nessun problema, utilizzando stessa rete domestica e stessa connessione wifi....qualche idea ??

**Comment by dentaku65** [comment]
ciao, devi impostare "wait for network" nelle impostazioni di rete, quindi riavvii, installi l'addon e riavvii di nuovo.
http://www.mimediacenter.info/foro/viewtopic.php?f=36&t=7474

**Comment by ginobyte** [comment]
Mille grazie, funziona !!! solo che ora se invece che guardare una serio o un film in streaming, gli dico di scaricarlo mi da un errore...qui il log è un po inarbugliato....tieni conto che sono partito da una SD schratch da 16Gb e ho, con diskimage, installato Openelec, e attivato il client PVR per vedere le TV...grazie mille per l'aiuto...

**Comment by dentaku65** [comment]
non vedo il log... mettilo su pastebin

**Comment by ginobyte** [comment]
http://pastebin.com/d1pb9bkS

spero di avere fatto bene tutto....grazie mille

**Comment by dentaku65** [comment]
come si chiama la directory dove fai download dei file?

**Comment by ginobyte** [comment]
Quella di default ; /storage/.kodi/userdata/addon_data/plugin.video/streamondemand/downloads

**Comment by dentaku65** [comment]
L'errore è che trova un carattere non unicode, probabilmente nel file che scarichi (es. un accento) e quindi và in errore non potendolo tradurre, se è così è da sistemare, ti succede con tutti i canali e con qualsiasi tentativo di download? Potresti cambiare path e salvarlo su un'altra risorsa che non sia openlec?

**Comment by ginobyte** [comment]
Provo stasera ad attaccare una chiavetta e usare quella come
repository....ti faccio sapere.

Grazie

Il giorno 21 aprile 2016 08:16, dentaku65 <notifications@github.com> ha
scritto:
