### ISSUE TITLE
apple tv 4gen

### ISSUE THREAD

**Issue by matteoivand** [Zanzibar82/plugin.video.streamondemand#33]
salve a tutti ragazzi ... 
vorrei segnalare un piccolo problema su apple tv...
la vostra repo non va in aggiornamento e non funziona mentre la versione 515 funziona (sempre senza aggiornarsi... pero funziona ).... come mai?

**Comment by Zanzibar82** [comment]
Aggiornare all'ultima versione dalla 5.1.5 o comunque versioni troppo datate comporta malfunzionamenti perchè troppo diverse le versioni nella loro struttura. Inoltre non c'è un repo ufficiale per il momento dal quale scaricare l'addon, ed ancora nessuno di noi sviluppatori possiede un'apple tv 4 per poter testare le modifiche. Senza contare che la versione di kodi presente per il dispositivo in questione è ancora imperfetto, e senza un file log possiamo solo tirare ad indovinare.

**Comment by matteoivand** [comment]
Hai perfettamente ragione !!! 
C'è solo da aspettare una versione più stabile ... Grazie per la risposta 

Inviato da iPad

**Comment by dentaku65** [comment]
ATV4 non è compatibile con Kodi e di conseguenza con i suoi addon

**Comment by matteoivand** [comment]
Ma intanto la versione Alpha va egregiamente .... Con questo non voglio dire che non abbia ragione !!!!!
Ma comunque bisogna aspettare una release come minimo beta ;)
