### ISSUE TITLE
SoD 5.2.4 sul Repo

### ISSUE THREAD

**Issue by DjDiabolik** [Zanzibar82/plugin.video.streamondemand#34]
Ho visto che tale versione è stata rilasciata circa 30 giorni fà... ma come mai non è ancora stata caricata nel "Fusion" Reposity ?

**Comment by Zanzibar82** [comment]
...io manco lo sapevo che eravamo sul repo di Fusion, ahahaha... aspettiamo info da dentaku :D

**Comment by DjDiabolik** [comment]
Lol.... eppure il repo è linkato anche qua :)

**Comment by dentaku65** [comment]
Non lo sapevo che fossimo su fusion... volevo fare la richiesta una settimana fà, ma poi non l'ho fatto... ad ogni modo prenderanno la release che stà qua su github, quale hanno messo di versione?

**Comment by DjDiabolik** [comment]
Hanno messo la 2.5.3... il link della repo l'ho preso da questo github ed è lo stesso zip che si trova proprio nel github fusionbox.
Ah... ma da oggi l'addons sembra ko perché su qualsiasi parte accedo mi da errore e mi dice di controllare il log mentre ieri sera funzionava senza problemi..... forse c'è da aggiornare i canali? C'è un modo per farlo senza riavviare il kodi (in pratica lanciare manualmente quello che ora viene fatto ad ogni avvio) ?

**Comment by DjDiabolik** [comment]
Cmq dopo un riavvio di Osmc (e quindi l'aggiornamento dei server e tutto quello che fa all'avvio) tutto è tornato a funzionare. A questo punto c'è una feature x lanciare questo aggiornamento a mano senza riavviare? se non c'è potrebbe essere una feature da aggiungere.... :)

**Comment by Zanzibar82** [comment]
Mi sa che ti si è corrotta l'installazione durante un aggiornamento. Capita anche a me qualchr volta se all'avvio di kodi non aspetto l'aggiornamento ed accedo subito all'addon. Disinstalla SoD, reinstallalo scaricando lo zip dalla pagina "releases", poi riavvia kodi ed aspetta che si aggiornino canali e server.

**Comment by DjDiabolik** [comment]
No ma che.... sicuramente è che avevo lasciato acceso il mio Pi2 e i server nel frattempo sono cambiati quindi appunto dopo un riavvio e quindi l'aggiornamento del tutto è tutto tornato a funzionare senza problemi.
Proprio per questo mi chiedevo se eventualmente c'è un modo per lanciare questo aggiornamento manualmente senza dover riavviare OSMC nel mio caso :)

**Comment by dentaku65** [comment]
No non si può, solo nel caso di una nuova release o di una reinstallazione; per OSMC come per Openelec consiglio di abilitare la feature di rete "wait for network"... che comunque implementeremo direttamente nel codice prossimamente... ad ogni modo puoi mettere il link di fusionbox?

**Comment by DjDiabolik** [comment]
Ok attiverò il wait for network nelle impostazioni domani.... se non sbaglio è da qualche parte nelle impostazioni di rete in osmc :)

Cmq sia per il fusionbox allora io ho preso il link direttamente dalla home page di questo github.. esattamente da questa pagina:
https://github.com/Zanzibar82

C'è un link che mi ha portato a questa:
https://github.com/Zanzibar82/FusionBox-repo

Appena aperto scorrendo la lista dei file ti accorgi subito che la versione della repo è la 5.2.3........ poi se vai a vedere l'ultimo file è proprio lo zip per installare la repo nel kodi... per la precisione questo:
https://github.com/Zanzibar82/FusionBox-repo/blob/master/repository.fusionbox.zip

Che poi appunto sono gli stessi identici file che ritroviamo qua:
https://github.com/FusionwareIT/FusionBox-repo

**Comment by dentaku65** [comment]
lol... Zanzi ma hai linkato il repo?

**Comment by DjDiabolik** [comment]
In che senso ho linkato il repo ?

**Comment by dentaku65** [comment]
diceva a zanzibar

**Comment by DjDiabolik** [comment]
Lol ah ok...... ma cmq non credo sia un problema soprattutto se anche la 5.2.3 ha la feature dell'autoaggiornamento.............. cioè alla fine se anche la repo non è aggiornata e l'addons si aggiorna da se appunto uno alla fine ottiene sempre l'ultima dopo il primo avvio... o no ?

**Comment by DjDiabolik** [comment]
Ragazzi una domanda stupida e anche un pò OT se volete........ ma dopo che sulla 5.2.5 è stato implementato il "Wait for Network" posso disattivare quello nelle impostazioni di rete di OSMC ?

**Comment by Zanzibar82** [comment]
Qualche tempo fa per riparare un server capitai su quel repo "fusion" , dove trovai il nostro SoD con qualche modifica, tra cui il server che intendevo riparare, che era funzionante.
Non voglio pensare fosse solo una versione vecchia del file :D

**Comment by dentaku65** [comment]
rifatto oggi il wait for network ..disabilitato su osmc funge

**Comment by DjDiabolik** [comment]
@dentaku65 ho visto........aggiornerò alla 5.2.6 tanto lo fa in automatico :)

Mica perchè... osmc col wait for network sembrava dare problemi qua e la e alcuni riportano anche dei freeze qua e la col wait attivato......... quindi io l'ho disattivato.

OT: Tralaltro osmc su pi2 nelle impostazioni di rete sembra frezzare ed avere qualche bug perchè sembra andare tutto a rilento quanto si entra nelle impostazioni di rete....... l'ho già segnalato sul forum e i developers m'hanno infermato che sono consapevoli del problema e che cercheranno di fixare in futuro.
