### ISSUE TITLE
Errore SoD su kodi + retropie

### ISSUE THREAD

**Issue by artic89** [Zanzibar82/plugin.video.streamondemand#35]
Salve volevo segnalare che anch io ho il problema che mi da errore quando cerco di entrare nei canali, da quello che ho visto  molti altri hanno questo problema su openelec, io però uso retropie con kodi e non ho l'opzione di attendere la connessione , quindi cosa posso fare? grazie per l'ottimo lavoro

**Comment by dentaku65** [comment]
La release 5.2.5 dovrebbe avere questo fix
https://github.com/Zanzibar82/plugin.video.streamondemand/blob/master/changelog.txt

**Comment by artic89** [comment]
fatto l'aggiornamento ma nulla è cambiato http://pastebin.com/Cb5by8JR

**Comment by dentaku65** [comment]
non mi risulta alcun riferimento a SOD nel log...

**Comment by artic89** [comment]
provo a cancellare la directory dell addon e  re installo?

**Comment by mky180** [comment]
Ho lo stesso identico problema con la stessa configurazione (retropie con kodi)

**Comment by dentaku65** [comment]
Una volta che il device è connesso e in una situazione pulita installa la 5.2.4 e aprendola ti dovrebbe proporre l'aggiornamento alla 5.2.5, prova ad aggiornare la versione in questo modo; una volta aggiornata prova a riavviare retropie...

**Comment by artic89** [comment]
messo la 5.2.4, apro mi dice impossibile verificare presenza di aggiornamenti, provo a fare l'update tramite zip, riavvio ma nulla è cambiato, il raspi è collegato ad internet tramite ethernet e lo streaming funzia sulla 5.1.9, questo è il log http://pastebin.com/s2r44vx7

**Comment by dentaku65** [comment]
E' un problema di retropie, visto che anche nel loro wiki Kodi è in versione experimental https://github.com/retropie/retropie-setup/wiki
SOD funziona sui sistemi pienamente supportati

**Comment by artic89** [comment]
ho risolto mettendo manualmente i file della cartella server e channel,, togliendo gli aggiornamenti automatici

**Comment by mky180** [comment]
Funziona anche dopo che riavii kodi? Perché anche io ho spostato quei file ma al riavvio si cancellano nonostante abbia disabilitato gli aggiornamenti automatici
