### ISSUE TITLE
More Anime is possible?

### ISSUE THREAD

**Issue by vinceplayer** [Zanzibar82/plugin.video.streamondemand#46]
Congratulations the amazing plug-in , There is nly one channel dedicated to ANIME( toonItalia ) but this last has a 480p video alone and some videos are no longer , it would be possible to ader ther Sources (for example vvvvid ecc ) ?
thank you so much

**Comment by DjDiabolik** [comment]
Possiamo parlare italiano qua....... i developers se ho capito bene sono italiani.

Cmq sia sarebbe una cosa figa poter aggiungere VVVVID.IT al sito anche se c'è già un'addons per questo sito ma non è + supportato e non indicizza + i contenuti correttamente dopo alcuni aggiornamenti del sito stesso......

**Comment by dentaku65** [comment]
Ciao, i canali che devono essere aggiunti suggerirei di indicarli sul forum non qui

**Comment by DjDiabolik** [comment]
Forum ? Quale forum ? :) Link per favore :)
