### ISSUE TITLE
Richiesta Feature - Richiesta per registra... è possibile ?

### ISSUE THREAD

**Issue by DjDiabolik** [Zanzibar82/plugin.video.streamondemand#47]
Allora ragazzi... utilizzo da qualche settimana questo fantastico addons.... praticamente se ho capito bene la "Ricerca Globale" si, diciamo, appoggia a "TheMoviedb.org" per trovare gli eventuali titoli giusto ? Poi una volta che tu hai trovato ciò che cerchi in pratica fa una ricerca cercando di interrogare tutti i vari siti................ la mia prima domanda è:
Ma che differenza c'è allora con la ricerca globale che si può fare direttamente nei canali ?

Poi veniamo quindi alla Feature richiesta........ ho visto che non c'è la possibilità di fare una ricerca in base al "Regista"... cioè ad esempio sul sito tramite persone ho trovato questo:
https://www.themoviedb.org/person/14999-george-a-romero

Ma se vado su "Ricerca Persone" e do "George romero" non ottengo risultati................. molto strano.....

**Comment by dentaku65** [comment]
se cerchi solo romero?

**Comment by DjDiabolik** [comment]
Lol va bè io ho fatto un'esempio.......... cioè obbiettivamente se cerchi solo "Romero" non esce niente... cosi come non mi esce niente se cerco "George Romero". Per far uscire qualcosa ho visto che devo mettere "George A." allora escono appunto i vari risultati che sembrano essere appunto gli stessi che escono anche facendo la ricerca da browser.

Perchè però se cerco solo "Romero" non esce niente......... forse perchè sul sito facendo questa ricerca:
https://www.themoviedb.org/search?query=Romero

Sotto è possibile cambiare pagina.... mentre qua per le ricerche cosi generiche restituisce un numero limitato di risultati............
Quindi in pratica non sarebbe una richiesta di feature ma forse migliorare la ricerca ?

**Comment by dentaku65** [comment]
Allora se parli della feature ricerca grlobale -> cerca per persone
la feature funziona correttamente, nel senso che restituisce i risultati anche di una ricerca parziale (es. allen) restituisce tutti gli allen; se sono oltre la pagna è vero non c'e' la pagina successiva (sarà da implementare); se cerchi George Romero restituisce correttamente George A. Romero... da quale sistema esegui che come risutato hai la ricrca vuota?

**Comment by DjDiabolik** [comment]
Allora...... diciamo che la cosa riguarda appunto la Ricerca Globale -> Cerca Persone :)
Allora in pratica se io cerco "George" non esce la ricerca vuota.... ma bensi escono un pò di risultati ed essendo appunto una ricerca generica ne restituisce parecchi di risultati e appunto sarebbe da implementare la pagina successiva :)

Invece ti confermo che ieri sera ho fatto aggiornare alla versione 5.2.7 e ho fatto una ricerca mettendo "George Romero" ed infatti esce un solo risultato che poi è "George A. Romero" :)

Eppure avevo provato anche questa cosa con la "vecchia" 5.2.6 e mi usciva la ricerca vuota.... boh... vacci a capire qualcosa :)

A quel punto l'unica cosa che sarebbe da implementare è la "pagina successiva"......

**Comment by dentaku65** [comment]
Su qiale sistema usi Kodi?
