### ISSUE TITLE
problemi generici nella ricerca

### ISSUE THREAD

**Issue by biagioDonato** [Zanzibar82/plugin.video.streamondemand#51]
Ciao a tutti,
Sto usando la versione 5.2.6 su ubuntu per arm
ultimamente sto avendo dei problemi sia in fase di ricerca che anche accedendo nella sezione "scegli una categoria/film", di seguito il log

`21:56:10 T:2744341536  NOTICE: -->Python Interpreter Initialized<--
21:56:10 T:2744341536  NOTICE: streamondemand.core.config PLATFORM_NAME=kodi-isengard
21:56:10 T:2744341536  NOTICE: streamondemand.core.config runtime path = /home/odroid/.kodi/addons/plugin.video.streamondemand
21:56:10 T:2744341536  NOTICE: streamondemand.core.config data path = /home/odroid/.kodi/userdata/addon_data/plugin.video.streamondemand/
21:56:10 T:2744341536  NOTICE: streamondemand.core.config temp path = /home/odroid/.kodi/temp/test
21:56:10 T:2744341536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'channel' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/default.py", line 28, in <module>
                                                launcher.run()
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/platformcode/launcher.py", line 108, in run
                                                logger.info("streamondemand.platformcode.launcher running channel %s %s" % (channel.__name__ , channel.__file__))
                                            UnboundLocalError: local variable 'channel' referenced before assignment
                                            -->End of Python script error report<--
21:56:10 T:3033625136   ERROR: GetDirectory - Error getting plugin://plugin.video.streamondemand/?action=mainlist&category=Ricerca%20Globale&channel=biblioteca
21:56:10 T:3033625136   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamondemand/?action=mainlist&category=Ricerca%20Globale&channel=biblioteca) failed`

`21:58:45 T:2709734432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'channel' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/default.py", line 28, in <module>
                                                launcher.run()
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/platformcode/launcher.py", line 108, in run
                                                logger.info("streamondemand.platformcode.launcher running channel %s %s" % (channel.__name__ , channel.__file__))
                                            UnboundLocalError: local variable 'channel' referenced before assignment
                                            -->End of Python script error report<--
21:58:45 T:3033625136   ERROR: GetDirectory - Error getting plugin://plugin.video.streamondemand/?action=mainlist&category=altadefinizione01&channel=altadefinizione01
21:58:45 T:3033625136   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamondemand/?action=mainlist&category=altadefinizione01&channel=altadefinizione01) failed
21:58:45 T:2709734432  NOTICE: Thread LanguageInvoker start, auto delete: false
`

**Comment by Zanzibar82** [comment]
Discutiamone sul forum ;)

**Comment by biagioDonato** [comment]
scusami mi puoi dare il link del forum, grazie

**Comment by Zanzibar82** [comment]
ecco a te, a presto! http://www.mimediacenter.info/foro/viewforum.php?f=36&sid=d818e6f028e4bd3053d44b5762285231
