### ISSUE TITLE
Contenuti HD di hd-streaming.it 

### ISSUE THREAD

**Issue by iz8mbw** [Zanzibar82/plugin.video.streamondemand#53]
Ciao.
I contenuti di hd-streaming.it del plugin sono visibili solo in SD e non anche in HD.
hd-streaming.it fornisce contenuti anche in 1080p "nativo" (senza downscaling di bitrate) anche in audio multicanale Dolby Digital o DTS.
Sarebbe carino poter sfruttare questa potenzialità (forse unica tra i vari siti di streaming) di hd-streaming.it anche nel plugin streamondemand.
Grazie.

**Comment by dentaku65** [comment]
Link di esempio?

**Comment by iz8mbw** [comment]
Link di esempio lato sito web o lato percorso/navigazione del plugin?

**Comment by dentaku65** [comment]
Lato sito web

**Comment by iz8mbw** [comment]
Ok, quando sarò a casa ti rispondo. Ma giusto per info, ieri sera tutti i contenuti della navigazione dal plugin del sito (di hd-streaming.it) erano vuoti, mostravano solo i 2 punti (..).

**Comment by iz8mbw** [comment]
Allora prendiamo come esempio "Alvin Superstar: nessuno ci può fermare".
Il sito rimanda a "http://adf.ly/1aeWhs" poi dopo i 5 secondi e dopo aver clicato "AVANTI" ti rimanda al file .mkv https://drive.google.com/file/d/0BxZRYVcK8FTVaW1scVhVR3RlLVk/view?pref=2&pli=1
E' un mkv in 1080p.
Ad ogni modo nessun contenuto di hd-streaming.it fruibile col pugin è in HD...
Puoi verificarlo tu stesso.

**Comment by dentaku65** [comment]
E' già stato sistemato
https://raw.githubusercontent.com/Zanzibar82/plugin.video.streamondemand/master/channels/hdstreamingit.py
http://www.mimediacenter.info/foro/viewtopic.php?f=36&t=7600

**Comment by iz8mbw** [comment]
In realtà quel problema segnalato è un altro....
Comunque continuo a vedere i contenuti non in HD... Sono andato nei settaggi del plugin e anziché lasciare "Guarda in alta qualità" o selezionato "Chiedi" e così facendo riesco a vedere il contenuto in 1080p.
Quindi, probabilmente, il "Guarda in alta qualità" non funziona sempre....
Ci potete dare un'occhio?
Grazie

**Comment by dentaku65** [comment]
I file sono quelli presenti sul sito; come tutti gli altri canali lo scraping prende quello che c'e', se c'e' in hd lo mostra. "Chiedi" è l'impostazione di default del plugin

**Comment by iz8mbw** [comment]
OK chiaro. In questo particolare caso il file in questione è disponibile in 1080p, 720p e diverse altre risoluzioni più basse.
SE lascio "Chiedi" (che è di default) mi comprare la lista da 1080p a scendere alle risoluzioni più basse e se seleziono 1080p mi viene mostrato in 1080p.
SE lascio "Guarda in alta qualità" in reatà NON parte in 1080p (o nella maggiore qualità disponibile) ma in una più bassa SD (quindi nè 1080p o nè 720p).
QUINDI in questo caso e immagino in tutti gli altri casi simili (cioè dove lo stesso contenuto è mostrabile in più risoluzioni), il settaggio "Guarda in alta qualità" non funziona o non funziona come io mi aspetto che funzioni e cioè: mostra il contenuto nella risoluzione più alta disponibile.

Ripeto, sempre se fosse possibile e a "tempo perso", sarebbe carino che l'opzione "Guarda in alta qualità" faccia partire di default la massima risoluzione possibile del contenuto (ovviamente se c'è la possibilità di riprodurre quel contenuto con più risoluzioni).
Grazie.
