### ISSUE TITLE
errore su win7

### ISSUE THREAD

**Issue by sgiannulli** [Zanzibar82/plugin.video.streamondemand#62]
`22:43:35 T:196   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
22:43:35 T:196   ERROR: CCurlFile::Open failed with code 0 for http://feeds.kodi.tv/latest_xbmc_addons
22:46:15 T:3728   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
22:46:21 T:2340   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name servertools
                                            Traceback (most recent call last):
                                              File "C:\Users\sandro\AppData\Roaming\Kodi\addons\plugin.video.streamondemand\default.py", line 28, in <module>
                                                launcher.run()
                                              File "C:\Users\sandro\AppData\Roaming\Kodi\addons\plugin.video.streamondemand\platformcode\launcher.py", line 146, in run
                                                from platformcode import xbmctools
                                              File "C:\Users\sandro\AppData\Roaming\Kodi\addons\plugin.video.streamondemand\platformcode\xbmctools.py", line 15, in <module>
                                                from servers import servertools
                                            ImportError: cannot import name servertools
                                            -->End of Python script error report<--`
ciao,
non capisco se questo errore dipende dall' addon o da altro; si ripropone in tutte le ricerche
Kodi 16.1 su windows 7
grazie

**Comment by Zanzibar82** [comment]
Hai impostato i DNS di google?

**Comment by sgiannulli** [comment]
a dire il vero uso una VPN e non posso modificare i DNS.
La cosa strana è che la 5.2.7 su un raspberry usando la VPN funziona, sulla macchina Win7 la 5.2.8 mi da tutti quegli errori.......faccio qualche prova

**Comment by sgiannulli** [comment]
disinstallato e reinstallato e adesso funziona
grazie per il grande lavoro
