### ISSUE TITLE
Link SerieHD non funzionanti

### ISSUE THREAD

**Issue by 8yql01ya09** [Zanzibar82/plugin.video.streamondemand#65]
Vengono listate le serie e le puntate ma quando si seleziona una puntata non appaiono i corrispondenti link videomega e openload.

**Comment by axlt2002** [comment]
Ciao, sono nuovo a questo fantastico add-on.
Confermo il problema riportato sopra.
Colgo l'occasione per chiedere se è corretto il fatto che anzichè il titolo dell'episodio venga visualizzato il numero dellsa serie e quello dell'episodio (ad esempio 1x01).
Grazie per il supporto!

**Comment by Kolifanes** [comment]
Grazie a @Dr-Zer0. Ma il fix è parziale. Viene visualizzato solo OpenLoad. Niente VideoMega.

**Comment by Dr-Zer0** [comment]
Sistemato definitivamente!
Godetevi tutti i mirror a tutte le risoluzioni.
Cia
