### ISSUE TITLE
So che non centra niente - Sul repository FusionBox c'è VideoMediaset - Ok ma non si installa e va in failed... ti/vi risulta ?

### ISSUE THREAD

**Issue by DjDiabolik** [Zanzibar82/plugin.video.streamondemand#67]
La domanda è nel titolo............. qualche tempo fà si citava un forum ma a mia richiesta di sapere quale forum nessuna risposta.....

Grazie in anticipo.

**Comment by dentaku65** [comment]
non è il nostro addon non saprei
https://github.com/streamondemand/plugin.video.streamondemand

**Comment by DjDiabolik** [comment]
Ah ok..... cmq è sul forum ufficiale kodi...
