### ISSUE TITLE
Link Openload

### ISSUE THREAD

**Issue by iz8mbw** [Zanzibar82/plugin.video.streamondemand#71]
Ciao.
I link di Openload non si aprono più...

Grazie

**Comment by cowboybkit** [comment]
Openload seem change encrypt algorithm. Please fix soon
Thanks

**Comment by Zanzibar82** [comment]
Syntax error:
Unknown command "soon"

**Comment by Dr-Zer0** [comment]
Fixed

**Comment by cagnulein** [comment]
@Dr-Zer0 for example does it work with https://openload.co/f/idv1yPfq-LQ/ ? It doesn't to me
