### ISSUE TITLE
Ma come funziona la biblioteca ???

### ISSUE THREAD

**Issue by DjDiabolik** [Zanzibar82/plugin.video.streamondemand#72]
Un paio di volte, mentre navigavo ad esempio per titoli, m'è capitato di premere e selezione erroneamente una dicitura che dice "Aggiungi alla Biblioteca" o qualcosa del genere.

Da li in poi non ho mai capito che cosa e dove vanno a finire questi link..... perchè nei preferiti non compaiono, ne in quella del kodi stessa (il favourites.xml) e ne nei preferiti dello stesso addons e quindi non sono riuscito a capire a cosa serve questa feature.

Poi magari è una cosa che non funziona solo su kodi installato su un Raspberry...............

**Comment by DjDiabolik** [comment]
Allora per puro caso ora stavo guardando e il tutto sembra finire qua:
/home/osmc/.kodi/userdata/addon_data/plugin.video.streamondemand/library/SERIES/

come si può vedere uso OSMC su un Pi2....... qui trovo 2 voci o meglio 2 cartelle con all'interno tutti file .strm che riportano allo stesso link aperto per avviare lo streaming stesso.
Cioè è una sorta di preferiti interni e ok sono li ma poi come li richiamo ?? Cioè non mi sembra ci sia niente per richiamarli dall'addons stesso e come detto nei preferiti non compare niente anche perchè i preferiti dell'addons in teoria dovrebbero finire qua:
/home/osmc/.kodi/userdata/addon_data/plugin.video.streamondemand/bookmarks/

**Comment by Dr-Zer0** [comment]
La prossima versione di SOD avrà una voce per richiamare questi preferiti.
Per adesso devi aggiungere in kodi video la cartella /home/osmc/.kodi/userdata/addon_data/plugin.video.streamondemand/library/SERIES/

**Comment by DjDiabolik** [comment]
Ah ottimo.......... oppure se non sbaglio puoi raggiungere quella cartella dal Gestore File :) anche se è, appunto, un FileManager molto spartano ma da li queste sorte di preferiti funzionano a meraviglia se si lancia un file .strm.
