### ISSUE TITLE
non si aggiorna alla 5.2.9

### ISSUE THREAD

**Issue by sgiannulli** [Zanzibar82/plugin.video.streamondemand#73]
ciao,
nonostante ci sia attivato l'aggiornamento automatico la mia versione è ferma alla 5.2.8.
Anche quando gli chiedo di aggiornarsi mi da come risposta che non ci sono nuove versioni.....però nelle release c'è già la 5.2.9.
Suggerimenti?
Grazie

**Comment by Zanzibar82** [comment]
Ciao, 
https://m.facebook.com/story.php?story_fbid=1050777598342917&id=892530264167652

**Comment by sgiannulli** [comment]
ops.......grazie
chiudo
